services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 2026-portfolio
    restart: always
    ports:
      - "4321:4321"
    environment:
      - HOST=0.0.0.0
      - PORT=4321
      - NODE_ENV=production